# Generated by Django 2.0.1 on 2018-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('S', 'Slovenski'), ('M', 'Mednarodni')], max_length=1)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=7)),
                ('project_ends', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.DateField(),
        ),
    ]
