# Generated by Django 2.0.1 on 2018-01-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20180122_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='workonproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.Projects'),
        ),
        migrations.AddField(
            model_name='workonproject',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.WorkDay'),
        ),
    ]
